import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// 1. 引入刚才写的 Provider
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "我的 AI 博客",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="zh-CN" suppressHydrationWarning>
      {/* 
        IT 知识点: suppressHydrationWarning 
        我们需要在 html 标签上加这个属性。
        因为 next-themes 会在网页加载时修改 html 的 class 属性，
        这会导致 React 报错说“服务器返回的 HTML 和浏览器实际渲染的不一样”，
        加这个属性就是告诉 React：“我知道这里会变，别报错”。
      */}
      <body className={`${inter.className} bg-background text-foreground`}>
        {/* 2. 用 Provider 包裹整个应用 */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}