import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// 1. 引入刚才写的 Provider
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Finn 的 AI 学习博客",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="zh-CN" suppressHydrationWarning>
      <body className={`${inter.className} bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-50 antialiased relative min-h-screen selection:bg-blue-500/30 selection:text-blue-900 dark:selection:text-blue-100`}>
        {/* === 背景装饰层 Start === */}
        <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none">
          {/* 1. 顶部左侧的蓝色光晕 */}
          <div className="absolute top-[-10%] left-[-10%] w-[500px] h-[500px] rounded-full bg-blue-400/20 dark:bg-blue-600/10 blur-[100px] mix-blend-multiply dark:mix-blend-screen animate-pulse-slow" />
          
          {/* 2. 顶部右侧的紫色光晕 */}
          <div className="absolute top-[-10%] right-[-10%] w-[600px] h-[600px] rounded-full bg-purple-400/20 dark:bg-purple-600/10 blur-[100px] mix-blend-multiply dark:mix-blend-screen animate-pulse-slow delay-1000" />
          
          {/* 3. 底部中间的粉色光晕 */}
          <div className="absolute bottom-[-20%] left-[20%] w-[800px] h-[800px] rounded-full bg-pink-400/20 dark:bg-pink-600/10 blur-[120px] mix-blend-multiply dark:mix-blend-screen animate-pulse-slow delay-2000" />
          
          {/* 4. 点阵纹理覆盖层 (使用 SVG 背景图) */}
          <div className="absolute inset-0 bg-[url('/grid.svg')] opacity-[0.03] dark:opacity-[0.05]" />
        </div>
        {/* === 背景装饰层 End === */}

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}